### ISSUE TITLE
Organizer labels - css

### ISSUE THREAD

**Issue by avaliani** [karma-exchange-org/karma-exchange#182]
I did a quick peak at some of the CSS that github is using via chrome. I think we can copy it to create organizer labels and other labels.

``` css
<span class="labels">
          <span class="label labelstyle-84b6eb darker" data-name="enhancement">enhancement</span>
      </span>
```

Blue background, black text

``` css
media="screen"
span.labelstyle-84b6eb {
background-color: #84b6eb !important;
color: #1c2733 !important;
}
```

Other key css snippets:

``` css
media="all"
.list-group-item .label {
display: inline-block;
font-size: 11px;
padding: 2px 4px;
border-radius: 2px;
box-shadow: inset 0 -1px 0 rgba(0,0,0,0.12);
}

media="all"
.list-group-item .label.darker {
text-shadow: 0 1px 0 rgba(255,255,255,0.4);
}

media="all"
.label {
font-size: 11px;
fill: #555;
stroke: none;
}

media="all"
body, input, select, textarea, button {
font: 13px Helvetica, arial, freesans, clean, sans-serif;
}
```

Inherited css

``` css
-webkit-box-shadow: rgba(0, 0, 0, 0.117647) 0px -0.9090908765792847px 0px 0px inset;
background-color: rgb(132, 182, 235);
border-bottom-left-radius: 1.9886363744735718px;
border-bottom-right-radius: 1.9886363744735718px;
border-top-left-radius: 1.9886363744735718px;
border-top-right-radius: 1.9886363744735718px;
box-shadow: rgba(0, 0, 0, 0.117647) 0px -0.9090908765792847px 0px 0px inset;
color: rgb(28, 39, 51);
display: inline-block;
fill: #555555;
font-family: Helvetica, arial, freesans, clean, sans-serif;
font-size: 10.909090995788574px;
font-style: normal;
font-variant: normal;
font-weight: bold;
height: 13.63636302947998px;
line-height: 12.727272033691406px;
list-style-type: disc;
padding-bottom: 1.9886363744735718px;
padding-left: 3.9914772510528564px;
padding-right: 3.9914772510528564px;
padding-top: 1.9886363744735718px;
stroke: none;
text-align: left;
text-shadow: rgba(255, 255, 255, 0.4) 0px 0.9090908765792847px 0px;
width: 70.90908813476563px;
```

Red bug label.

``` css
<span class="labels">
          <span class="label labelstyle-fc2929 lighter" data-name="bug">bug</span>
      </span>
```

I also noticed they have an inline style-sheet which contains much of the label info. Along with colors for when the label is selected.

``` css
<style type="text/css" media="screen">

span.labelstyle-84b6eb {  background-color: #84b6eb !important;  color: #1c2733 !important;}.labelstyle-84b6eb.selected {  background-color: #84b6eb !important;  color: #1c2733 !important;}.label-select-menu .labelstyle-84b6eb.selected {  background:rgba(132, 182, 235, 0.12) !important;  color: #557699 !important;}

</style>
```
